services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: factory_mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qcTQKtbz30wTFp_V
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'qcTQKtbz30wTFp_V' -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mssql_data:
